import 'package:insta_clone/server/random_user_generator.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class randomUserInfo {
/*
{
  "seed": "fc3555ce532506d2",
  "results": 1,
  "page": 1,
  "version": "1.4"
} 
*/

  String? seed;
  int? results;
  int? page;
  String? version;

  randomUserInfo({
    this.seed,
    this.results,
    this.page,
    this.version,
  });
  randomUserInfo.fromJson(Map<String, dynamic> json) {
    seed = json['seed']?.toString();
    results = json['results']?.toInt();
    page = json['page']?.toInt();
    version = json['version']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['seed'] = seed;
    data['results'] = results;
    data['page'] = page;
    data['version'] = version;
    return data;
  }
}

class randomUserResultsPicture {
/*
{
  "large": "https://randomuser.me/api/portraits/men/43.jpg",
  "medium": "https://randomuser.me/api/portraits/med/men/43.jpg",
  "thumbnail": "https://randomuser.me/api/portraits/thumb/men/43.jpg"
} 
*/

  String? large;
  String? medium;
  String? thumbnail;

  randomUserResultsPicture({
    this.large,
    this.medium,
    this.thumbnail,
  });
  randomUserResultsPicture.fromJson(Map<String, dynamic> json) {
    large = json['large']?.toString();
    medium = json['medium']?.toString();
    thumbnail = json['thumbnail']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['large'] = large;
    data['medium'] = medium;
    data['thumbnail'] = thumbnail;
    return data;
  }
}

class randomUserResultsId {
/*
{
  "name": "INSEE",
  "value": "1460962731953 55"
} 
*/

  String? name;
  String? value;

  randomUserResultsId({
    this.name,
    this.value,
  });
  randomUserResultsId.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    value = json['value']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['value'] = value;
    return data;
  }
}

class randomUserResultsRegistered {
/*
{
  "date": "2005-07-30T14:54:32.561Z",
  "age": 17
} 
*/

  String? date;
  int? age;

  randomUserResultsRegistered({
    this.date,
    this.age,
  });
  randomUserResultsRegistered.fromJson(Map<String, dynamic> json) {
    date = json['date']?.toString();
    age = json['age']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['date'] = date;
    data['age'] = age;
    return data;
  }
}

class randomUserResultsDob {
/*
{
  "date": "1946-10-07T06:37:23.476Z",
  "age": 76
} 
*/

  String? date;
  int? age;

  randomUserResultsDob({
    this.date,
    this.age,
  });
  randomUserResultsDob.fromJson(Map<String, dynamic> json) {
    date = json['date']?.toString();
    age = json['age']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['date'] = date;
    data['age'] = age;
    return data;
  }
}

class randomUserResultsLogin {
/*
{
  "uuid": "95977e2c-9e7b-4073-9747-102604647473",
  "username": "goldenladybug211",
  "password": "holidays",
  "salt": "K5BTcBmL",
  "md5": "fd54a27cfe98e620993f1d0553dd9b49",
  "sha1": "0288f8499e22ded0e92403c6e397ef9c6d57c5ae",
  "sha256": "cd1eca5980e8e49c1b299559c70d624d8b86938eebea449c679b4c71c4db4adc"
} 
*/

  String? uuid;
  String? username;
  String? password;
  String? salt;
  String? md5;
  String? sha1;
  String? sha256;

  randomUserResultsLogin({
    this.uuid,
    this.username,
    this.password,
    this.salt,
    this.md5,
    this.sha1,
    this.sha256,
  });
  randomUserResultsLogin.fromJson(Map<String, dynamic> json) {
    uuid = json['uuid']?.toString();
    username = json['username']?.toString();
    password = json['password']?.toString();
    salt = json['salt']?.toString();
    md5 = json['md5']?.toString();
    sha1 = json['sha1']?.toString();
    sha256 = json['sha256']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['uuid'] = uuid;
    data['username'] = username;
    data['password'] = password;
    data['salt'] = salt;
    data['md5'] = md5;
    data['sha1'] = sha1;
    data['sha256'] = sha256;
    return data;
  }
}

class randomUserResultsLocationTimezone {
/*
{
  "offset": "+3:30",
  "description": "Tehran"
} 
*/

  String? offset;
  String? description;

  randomUserResultsLocationTimezone({
    this.offset,
    this.description,
  });
  randomUserResultsLocationTimezone.fromJson(Map<String, dynamic> json) {
    offset = json['offset']?.toString();
    description = json['description']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['offset'] = offset;
    data['description'] = description;
    return data;
  }
}

class randomUserResultsLocationCoordinates {
/*
{
  "latitude": "-14.9166",
  "longitude": "-140.0245"
} 
*/

  String? latitude;
  String? longitude;

  randomUserResultsLocationCoordinates({
    this.latitude,
    this.longitude,
  });
  randomUserResultsLocationCoordinates.fromJson(Map<String, dynamic> json) {
    latitude = json['latitude']?.toString();
    longitude = json['longitude']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['latitude'] = latitude;
    data['longitude'] = longitude;
    return data;
  }
}

class randomUserResultsLocationStreet {
/*
{
  "number": 4744,
  "name": "Rue de Bonnel"
} 
*/

  int? number;
  String? name;

  randomUserResultsLocationStreet({
    this.number,
    this.name,
  });
  randomUserResultsLocationStreet.fromJson(Map<String, dynamic> json) {
    number = json['number']?.toInt();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['number'] = number;
    data['name'] = name;
    return data;
  }
}

class randomUserResultsLocation {
/*
{
  "street": {
    "number": 4744,
    "name": "Rue de Bonnel"
  },
  "city": "Toulouse",
  "state": "Corrèze",
  "country": "France",
  "postcode": 81405,
  "coordinates": {
    "latitude": "-14.9166",
    "longitude": "-140.0245"
  },
  "timezone": {
    "offset": "+3:30",
    "description": "Tehran"
  }
} 
*/

  randomUserResultsLocationStreet? street;
  String? city;
  String? state;
  String? country;
  int? postcode;
  randomUserResultsLocationCoordinates? coordinates;
  randomUserResultsLocationTimezone? timezone;

  randomUserResultsLocation({
    this.street,
    this.city,
    this.state,
    this.country,
    this.postcode,
    this.coordinates,
    this.timezone,
  });
  randomUserResultsLocation.fromJson(Map<String, dynamic> json) {
    street = (json['street'] != null)
        ? randomUserResultsLocationStreet.fromJson(json['street'])
        : null;
    city = json['city']?.toString();
    state = json['state']?.toString();
    country = json['country']?.toString();
    postcode = json['postcode']?.toInt();
    coordinates = (json['coordinates'] != null)
        ? randomUserResultsLocationCoordinates.fromJson(json['coordinates'])
        : null;
    timezone = (json['timezone'] != null)
        ? randomUserResultsLocationTimezone.fromJson(json['timezone'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (street != null) {
      data['street'] = street!.toJson();
    }
    data['city'] = city;
    data['state'] = state;
    data['country'] = country;
    data['postcode'] = postcode;
    if (coordinates != null) {
      data['coordinates'] = coordinates!.toJson();
    }
    if (timezone != null) {
      data['timezone'] = timezone!.toJson();
    }
    return data;
  }
}

class randomUserResultsName {
/*
{
  "title": "Mr",
  "first": "Malone",
  "last": "Fournier"
} 
*/

  String? title;
  String? first;
  String? last;

  randomUserResultsName({
    this.title,
    this.first,
    this.last,
  });
  randomUserResultsName.fromJson(Map<String, dynamic> json) {
    title = json['title']?.toString();
    first = json['first']?.toString();
    last = json['last']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    data['first'] = first;
    data['last'] = last;
    return data;
  }
}

class randomUserResults {
/*
{
  "gender": "male",
  "name": {
    "title": "Mr",
    "first": "Malone",
    "last": "Fournier"
  },
  "location": {
    "street": {
      "number": 4744,
      "name": "Rue de Bonnel"
    },
    "city": "Toulouse",
    "state": "Corrèze",
    "country": "France",
    "postcode": 81405,
    "coordinates": {
      "latitude": "-14.9166",
      "longitude": "-140.0245"
    },
    "timezone": {
      "offset": "+3:30",
      "description": "Tehran"
    }
  },
  "email": "malone.fournier@example.com",
  "login": {
    "uuid": "95977e2c-9e7b-4073-9747-102604647473",
    "username": "goldenladybug211",
    "password": "holidays",
    "salt": "K5BTcBmL",
    "md5": "fd54a27cfe98e620993f1d0553dd9b49",
    "sha1": "0288f8499e22ded0e92403c6e397ef9c6d57c5ae",
    "sha256": "cd1eca5980e8e49c1b299559c70d624d8b86938eebea449c679b4c71c4db4adc"
  },
  "dob": {
    "date": "1946-10-07T06:37:23.476Z",
    "age": 76
  },
  "registered": {
    "date": "2005-07-30T14:54:32.561Z",
    "age": 17
  },
  "phone": "01-23-24-24-22",
  "cell": "06-88-33-72-76",
  "id": {
    "name": "INSEE",
    "value": "1460962731953 55"
  },
  "picture": {
    "large": "https://randomuser.me/api/portraits/men/43.jpg",
    "medium": "https://randomuser.me/api/portraits/med/men/43.jpg",
    "thumbnail": "https://randomuser.me/api/portraits/thumb/men/43.jpg"
  },
  "nat": "FR"
} 
*/

  String? gender;
  randomUserResultsName? name;
  randomUserResultsLocation? location;
  String? email;
  randomUserResultsLogin? login;
  randomUserResultsDob? dob;
  randomUserResultsRegistered? registered;
  String? phone;
  String? cell;
  randomUserResultsId? id;
  randomUserResultsPicture? picture;
  String? nat;

  randomUserResults({
    this.gender,
    this.name,
    this.location,
    this.email,
    this.login,
    this.dob,
    this.registered,
    this.phone,
    this.cell,
    this.id,
    this.picture,
    this.nat,
  });
  randomUserResults.fromJson(Map<String, dynamic> json) {
    gender = json['gender']?.toString();
    name = (json['name'] != null)
        ? randomUserResultsName.fromJson(json['name'])
        : null;
    location = (json['location'] != null)
        ? randomUserResultsLocation.fromJson(json['location'])
        : null;
    email = json['email']?.toString();
    login = (json['login'] != null)
        ? randomUserResultsLogin.fromJson(json['login'])
        : null;
    dob = (json['dob'] != null)
        ? randomUserResultsDob.fromJson(json['dob'])
        : null;
    registered = (json['registered'] != null)
        ? randomUserResultsRegistered.fromJson(json['registered'])
        : null;
    phone = json['phone']?.toString();
    cell = json['cell']?.toString();
    id = (json['id'] != null) ? randomUserResultsId.fromJson(json['id']) : null;
    picture = (json['picture'] != null)
        ? randomUserResultsPicture.fromJson(json['picture'])
        : null;
    nat = json['nat']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['gender'] = gender;
    if (name != null) {
      data['name'] = name!.toJson();
    }
    if (location != null) {
      data['location'] = location!.toJson();
    }
    data['email'] = email;
    if (login != null) {
      data['login'] = login!.toJson();
    }
    if (dob != null) {
      data['dob'] = dob!.toJson();
    }
    if (registered != null) {
      data['registered'] = registered!.toJson();
    }
    data['phone'] = phone;
    data['cell'] = cell;
    if (id != null) {
      data['id'] = id!.toJson();
    }
    if (picture != null) {
      data['picture'] = picture!.toJson();
    }
    data['nat'] = nat;
    return data;
  }
}

class randomUser {
/*
{
  "results": [
    {
      "gender": "male",
      "name": {
        "title": "Mr",
        "first": "Malone",
        "last": "Fournier"
      },
      "location": {
        "street": {
          "number": 4744,
          "name": "Rue de Bonnel"
        },
        "city": "Toulouse",
        "state": "Corrèze",
        "country": "France",
        "postcode": 81405,
        "coordinates": {
          "latitude": "-14.9166",
          "longitude": "-140.0245"
        },
        "timezone": {
          "offset": "+3:30",
          "description": "Tehran"
        }
      },
      "email": "malone.fournier@example.com",
      "login": {
        "uuid": "95977e2c-9e7b-4073-9747-102604647473",
        "username": "goldenladybug211",
        "password": "holidays",
        "salt": "K5BTcBmL",
        "md5": "fd54a27cfe98e620993f1d0553dd9b49",
        "sha1": "0288f8499e22ded0e92403c6e397ef9c6d57c5ae",
        "sha256": "cd1eca5980e8e49c1b299559c70d624d8b86938eebea449c679b4c71c4db4adc"
      },
      "dob": {
        "date": "1946-10-07T06:37:23.476Z",
        "age": 76
      },
      "registered": {
        "date": "2005-07-30T14:54:32.561Z",
        "age": 17
      },
      "phone": "01-23-24-24-22",
      "cell": "06-88-33-72-76",
      "id": {
        "name": "INSEE",
        "value": "1460962731953 55"
      },
      "picture": {
        "large": "https://randomuser.me/api/portraits/men/43.jpg",
        "medium": "https://randomuser.me/api/portraits/med/men/43.jpg",
        "thumbnail": "https://randomuser.me/api/portraits/thumb/men/43.jpg"
      },
      "nat": "FR"
    }
  ],
  "info": {
    "seed": "fc3555ce532506d2",
    "results": 1,
    "page": 1,
    "version": "1.4"
  }
} 
*/

  List<randomUserResults?>? results;
  randomUserInfo? info;

  randomUser({
    this.results,
    this.info,
  });
  randomUser.fromJson(Map<String, dynamic> json) {
    if (json['results'] != null) {
      final v = json['results'];
      final arr0 = <randomUserResults>[];
      v.forEach((v) {
        arr0.add(randomUserResults.fromJson(v));
      });
      results = arr0;
    }
    info =
        (json['info'] != null) ? randomUserInfo.fromJson(json['info']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (results != null) {
      final v = results;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['results'] = arr0;
    }
    if (info != null) {
      data['info'] = info!.toJson();
    }
    return data;
  }
}
